name: Deploy to Google Cloud Functions

on: workflow_dispatch
#  push:
#    branches:
#      - deploy # deployブランチへのプッシュでトリガー

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          FUNCTION_NAME: hello_world

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy $FUNCTION_NAME \
            --project=$PROJECT_ID \
            --runtime=python39 \ # ランタイムを指定
            --trigger-http \
            --allow-unauthenticated
            --region=asia-northeast1
            --source=./src
