name: Deploy to Google Cloud Functions

on: workflow_dispatch
#  push:
#    branches:
#      - deploy # deployブランチへのプッシュでトリガー

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.0

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy hello_world \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --runtime=python39 \
            --trigger-http \
            --allow-unauthenticated \
            --region=asia-northeast1 \
            --source=./src
